export const SET_EMPLOYEE_ID = 'SET_EMPLOYEE_ID';

export const GET_CHALLENGES = 'GET_CHALLENGES';
export const UPVOTE_CHALLENGE = 'UPVOTE_CHALLENGE';
export const EDIT_CHALLENGE = 'EDIT_CHALLENGE';
export const CREATE_CHALLENGE = 'CREATE_CHALLENGE';

export const UPDATE_TAGS = 'UPDATE_TAGS';
